# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  

jobs:
  publish:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: install SSH key
      run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
            
    - name: connect and pull
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout main && git pull && exit"
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore ./Quan_ly_moi_truong_Web/Quan_ly_moi_truong_Web.sln

    - name: Build
      run: dotnet build ./Quan_ly_moi_truong_Web/Quan_ly_moi_truong_Web.sln --no-restore
      
    - name: Publish
      run: dotnet publish ./Quan_ly_moi_truong_Web/API/API.csproj --configuration Release
