# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  

jobs:
  deploy:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x' # Replace with your desired .NET version

      - name: Build and Publish
        run: |
          dotnet build --configuration Release
          dotnet publish ./Quan_ly_moi_truong_Web/API/API.csproj --configuration Release --output ./publish

      - name: Deploy to Azure VM
        uses: appleboy/winrm@v1
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          password: ${{ secrets.AZURE_VM_PASSWORD }}
          port: 5986
          script: |
            $session = New-PSSession -ComputerName $env:HOST -Credential (Get-Credential -UserName $env:AZURE_VM_USERNAME -Password $env:AZURE_VM_PASSWORD)
            Copy-Item -Path ./publish/* -Destination "C:\inetpub\wwwroot\urban-be" -Recurse -ToSession $session
            Remove-PSSession $session
